language: java
jdk:
    - oraclejdk8
install:
    - ./gradlew assemble
script:
    - ./gradlew check
after_success:
    - ./deployJavadocs.sh
    - ./gradlew test jacocoTestReport coveralls

notifications:
    email:
        on_success: change
        on_failure: change
env:
    global:
        - DEPLOY_GIT_NAME=TravisCI
        - DEPLOY_GIT_EMAIL=tavisci@noreply.corbatto.de
        - DEPLOY_COMMIT_MSG='Automatically updated JavaDocs for COMMIT_SHA on branch BRANCH.'